config/routes.rb
Like4me::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :user, :path => '/admin', :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :admin, :only  => [:index]
  get 'admin/settings' => 'admin#settings'
  post 'admin/settings' => 'admin#settings'
  delete 'admin/settings' => 'admin#settings'
  put 'admin/settings' => 'admin#settings'

  scope "admin" do
    resources :textpages, :except => :show
    resources :questions, :except => :show
    resources :posts, :except => :show
    resources :feedback, :except => [:create, :new, :edit, :update]
    resources :exchange, :except => [:create, :new, :edit, :update]
  end
  
  post 'sprypay/ipn' => 'sprypay#ipn'
  post 'sprypay/success' => 'sprypay#success'
  post 'sprypay/fail' => 'sprypay#fail'
  
  post '/ajax/do_not_show_info_win' => 'ajax#do_not_show_info_win'
  post '/ajax/check_info_win' => 'ajax#check_info_win'
  post '/ajax/like_post' => 'ajax#like_post'
  post '/ajax/check_like' => 'ajax#check_like'
  post '/ajax/subscribe_group' => 'ajax#subscribe_group'
  post '/ajax/check_subscribe' => 'ajax#check_subscribe'
  post '/ajax/update_balance' => 'ajax#update_balance'
  post '/ajax/service_repost' => 'ajax#service_repost'
  
  match "cabinet" => 'cabinet#index'
  get '/cabinet/orders'     => 'cabinet#orders'
  delete '/cabinet/orders'  => 'cabinet#orders'
  get '/cabinet/friends' => 'cabinet#friends'
  match '/cabinet/get_likes' => 'cabinet#get_likes'
  match '/cabinet/get_subscribers' => 'cabinet#get_subscribers'
  match '/cabinet/get_friends' => 'cabinet#get_friends'
 

  root :to => 'main#index'
  match 'faq' => 'main#faq'
  match 'buy' => 'main#buy'
  match 'blog' => 'main#blog'
  match 'blog/:id' => 'main#blog_details', :as => :blog_details
  get 'feedback' => 'main#feedback'
  post 'feedback' => 'main#feedback'
  match "/auth/:provider/callback" => "site_sessions#create"
  match "/signout" => "site_sessions#destroy", :as => :signout
  match "/auth/failure" => 'main#index'
  match '/cabinet/download_subscribers' => 'cabinet#download_subscribers' 
  post '/cabinet/check_like4me_subscribe' => 'cabinet#check_like4me_subscribe'
  post '/cabinet/download_list' => 'cabinet#download_list'
  match 'buy/(/:t)' => 'buy#index'
  get ':slug' => 'main#textpage'

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :question, :status
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json

  layout "admin"

  before_filter :authenticate_user!

  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_url }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to questions_url }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def get_last_questions
    @questions = Question.find(:all, :limit => 5)
    return @questions
  end
end

app/views/questions/_form.html.erb
<%= form_for(@question, :html => { :class => "form-horizontal" }) do |f| %>
<div class="form-actions">
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label" for="param_name">Вопрос</label>
    <div class="controls">
      <%= f.text_field :question %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="param_name">Ответ</label>
    <div class="controls">
        <%= f.cktext_area :answer %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="param_name">Скртый</label>
    <div class="controls">
      <%= f.select(:status, options_for_select([['Да', 1], ['Нет', 0]])) %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить", :class => "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/questions/edit.html.erb
<h4>Редактиврование вопроса</h4>

<%= render 'form' %>

<%= link_to 'Назад к списку', questions_path %>

app/views/questions/index.html.erb
<h4>Список вопросов</h4>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Вопрос</th>
    <th>Скрыт</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @questions.each do |question| %>
  <tr>
    <td><%= question.question %></td>
    <td><%= question.status %></td>
    <td><%= link_to image_tag('/im/edit.png'), edit_question_path(question) %></td>
    <td><%= link_to image_tag('/im/delete.png'), question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'Новый вопрос', new_question_path %>

app/views/questions/new.html.erb
<h4>Новый вопрос</h4>

<%= render 'form' %>

<%= link_to 'Назад к списку', questions_path %>