config/routes.rb
Like4me::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :user, :path => '/admin', :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :admin, :only  => [:index]
  get 'admin/settings' => 'admin#settings'
  post 'admin/settings' => 'admin#settings'
  delete 'admin/settings' => 'admin#settings'
  put 'admin/settings' => 'admin#settings'

  scope "admin" do
    resources :textpages, :except => :show
    resources :questions, :except => :show
    resources :posts, :except => :show
    resources :feedback, :except => [:create, :new, :edit, :update]
    resources :exchange, :except => [:create, :new, :edit, :update]
  end
  
  post 'sprypay/ipn' => 'sprypay#ipn'
  post 'sprypay/success' => 'sprypay#success'
  post 'sprypay/fail' => 'sprypay#fail'
  
  post '/ajax/do_not_show_info_win' => 'ajax#do_not_show_info_win'
  post '/ajax/check_info_win' => 'ajax#check_info_win'
  post '/ajax/like_post' => 'ajax#like_post'
  post '/ajax/check_like' => 'ajax#check_like'
  post '/ajax/subscribe_group' => 'ajax#subscribe_group'
  post '/ajax/check_subscribe' => 'ajax#check_subscribe'
  post '/ajax/update_balance' => 'ajax#update_balance'
  post '/ajax/service_repost' => 'ajax#service_repost'
  
  match "cabinet" => 'cabinet#index'
  get '/cabinet/orders'     => 'cabinet#orders'
  delete '/cabinet/orders'  => 'cabinet#orders'
  get '/cabinet/friends' => 'cabinet#friends'
  match '/cabinet/get_likes' => 'cabinet#get_likes'
  match '/cabinet/get_subscribers' => 'cabinet#get_subscribers'
  match '/cabinet/get_friends' => 'cabinet#get_friends'
 

  root :to => 'main#index'
  match 'faq' => 'main#faq'
  match 'buy' => 'main#buy'
  match 'blog' => 'main#blog'
  match 'blog/:id' => 'main#blog_details', :as => :blog_details
  get 'feedback' => 'main#feedback'
  post 'feedback' => 'main#feedback'
  match "/auth/:provider/callback" => "site_sessions#create"
  match "/signout" => "site_sessions#destroy", :as => :signout
  match "/auth/failure" => 'main#index'
  match '/cabinet/download_subscribers' => 'cabinet#download_subscribers' 
  post '/cabinet/check_like4me_subscribe' => 'cabinet#check_like4me_subscribe'
  post '/cabinet/download_list' => 'cabinet#download_list'
  match 'buy/(/:t)' => 'buy#index'
  get ':slug' => 'main#textpage'

end

app/models/textpage.rb
class Textpage < ActiveRecord::Base
  attr_accessible :content, :hidden, :slug, :title
end

app/controllers/textpages_controller.rb
class TextpagesController < ApplicationController
  # GET /textpages
  # GET /textpages.json

  
  layout "admin"

  before_filter :authenticate_user! 

  def index
    @textpages = Textpage.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /textpages/new
  # GET /textpages/new.json
  def new
    @textpage = Textpage.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /textpages/1/edit
  def edit
    @textpage = Textpage.find(params[:id])
  end

  # POST /textpages
  # POST /textpages.json
  def create
    @textpage = Textpage.new(params[:textpage])

    respond_to do |format|
      if @textpage.save
        format.html { redirect_to textpages_url }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /textpages/1
  # PUT /textpages/1.json
  def update
    @textpage = Textpage.find(params[:id])

    respond_to do |format|
      if @textpage.update_attributes(params[:textpage])
        format.html { redirect_to textpages_url  }
      else
        format.html { render action: "index" }
      end
    end
  end

  # DELETE /textpages/1
  # DELETE /textpages/1.json
  def destroy
    @textpage = Textpage.find(params[:id])
    @textpage.destroy

    respond_to do |format|
      format.html { redirect_to textpages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/textpages_helper.rb
module TextpagesHelper
  def get_textpages_list
    @textpages = Textpage.find(:all)
    return @textpages
  end

  def get_available_text_page
    @textpages = Textpage.find(:all, :conditions => { :hidden => 0 })
    return @textpages
  end
end

app/views/textpages/_form.html.erb
<%= form_for(@textpage, :html => { :class => "form-horizontal" }) do |f| %>
<div class="form-actions">
  <% if @textpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@textpage.errors.count, "error") %> prohibited this textpage from being saved:</h2>
      <ul>
      <% @textpage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label" for="param_name">Тайтл страницы</label>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="param_name">Контент страницы</label>
    <div class="controls">
      <%= f.cktext_area :content %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="param_name">URL</label>
    <div class="controls">
      <%= f.text_field :slug %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="param_name">Скртыая страница</label>
    <div class="controls">
      <%= f.select(:hidden, options_for_select([['Да', 1], ['Нет', 0]])) %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить", :class => "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/textpages/edit.html.erb
<h4>Редактироание страницы</h4>

<%= render 'form' %>

<%= link_to 'Назад к списку', textpages_path %>

app/views/textpages/index.html.erb
<h4>Список текстовых страниц</h4>

<table class="table table-striped"> 
  <thead>
  <tr>
    <th>Title</th>
    <th>URL</th>
    <th>Скрыта</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @textpages.each do |textpage| %>
  <tr>
    <td><%= textpage.title %></td>
    <td><%= textpage.slug %></td>
    <td><%= textpage.hidden %></td>
    <td><%= link_to image_tag('/im/edit.png'), edit_textpage_path(textpage) %></td>
    <td><%= link_to image_tag('/im/delete.png'), textpage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'Новая страница', new_textpage_path %>

app/views/textpages/new.html.erb
<h4>Новая страница</h4>

<%= render 'form' %>

<%= link_to 'Назад к списку', textpages_path %>