config/routes.rb
Like4me::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :user, :path => '/admin', :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :admin, :only  => [:index]
  get 'admin/settings' => 'admin#settings'
  post 'admin/settings' => 'admin#settings'
  delete 'admin/settings' => 'admin#settings'
  put 'admin/settings' => 'admin#settings'

  scope "admin" do
    resources :textpages, :except => :show
    resources :questions, :except => :show
    resources :posts, :except => :show
    resources :feedback, :except => [:create, :new, :edit, :update]
    resources :exchange, :except => [:create, :new, :edit, :update]
  end
  
  post 'sprypay/ipn' => 'sprypay#ipn'
  post 'sprypay/success' => 'sprypay#success'
  post 'sprypay/fail' => 'sprypay#fail'
  
  post '/ajax/do_not_show_info_win' => 'ajax#do_not_show_info_win'
  post '/ajax/check_info_win' => 'ajax#check_info_win'
  post '/ajax/like_post' => 'ajax#like_post'
  post '/ajax/check_like' => 'ajax#check_like'
  post '/ajax/subscribe_group' => 'ajax#subscribe_group'
  post '/ajax/check_subscribe' => 'ajax#check_subscribe'
  post '/ajax/update_balance' => 'ajax#update_balance'
  post '/ajax/service_repost' => 'ajax#service_repost'
  
  match "cabinet" => 'cabinet#index'
  get '/cabinet/orders'     => 'cabinet#orders'
  delete '/cabinet/orders'  => 'cabinet#orders'
  get '/cabinet/friends' => 'cabinet#friends'
  match '/cabinet/get_likes' => 'cabinet#get_likes'
  match '/cabinet/get_subscribers' => 'cabinet#get_subscribers'
  match '/cabinet/get_friends' => 'cabinet#get_friends'
 

  root :to => 'main#index'
  match 'faq' => 'main#faq'
  match 'buy' => 'main#buy'
  match 'blog' => 'main#blog'
  match 'blog/:id' => 'main#blog_details', :as => :blog_details
  get 'feedback' => 'main#feedback'
  post 'feedback' => 'main#feedback'
  match "/auth/:provider/callback" => "site_sessions#create"
  match "/signout" => "site_sessions#destroy", :as => :signout
  match "/auth/failure" => 'main#index'
  match '/cabinet/download_subscribers' => 'cabinet#download_subscribers' 
  post '/cabinet/check_like4me_subscribe' => 'cabinet#check_like4me_subscribe'
  post '/cabinet/download_list' => 'cabinet#download_list'
  match 'buy/(/:t)' => 'buy#index'
  get ':slug' => 'main#textpage'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :intro, :status, :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json

  layout "admin"

  before_filter :authenticate_user!

  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to posts_url }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def get_last_posts
    @posts = Post.find(:all, :conditions => { :status => 0 }, :limit => 3, :order => 'id DESC' )
    return @posts
  end

  def get_last_posts_admin
    @posts = Post.find(:all, :conditions => { :status => 0 }, :limit => 10, :order => 'id DESC' )
    return @posts
  end
end

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :class => "form-horizontal" }) do |f| %>
<div class="form-actions">
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label" for="param_name">Название</label>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="param_name">Аннотация</label>
    <div class="controls">
        <%= f.cktext_area :intro %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="param_name">Содержание</label>
    <div class="controls">
        <%= f.cktext_area :content %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="param_name">Скрыт</label>
    <div class="controls">
      <%= f.select(:status, options_for_select([['Да', 1], ['Нет', 0]])) %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить", :class => "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<h4>Редактирование поста</h4>

<%= render 'form' %>

<%= link_to 'Вернуться к списку', posts_path %>

app/views/posts/index.html.erb
<h4>Список постов</h4>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Название</th>
    <th>Скрыт</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.status %></td>
    <td><%= link_to image_tag('/im/edit.png'), edit_post_path(post) %></td>
    <td><%= link_to image_tag('/im/delete.png'), post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'Новый пост', new_post_path %>

app/views/posts/new.html.erb
<h4>Новый пост</h4>

<%= render 'form' %>

<%= link_to 'Назад к списку', posts_path %>