config/routes.rb
Like4me::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :user, :path => '/admin', :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :admin, :only  => [:index]
  get 'admin/settings' => 'admin#settings'
  post 'admin/settings' => 'admin#settings'
  delete 'admin/settings' => 'admin#settings'
  put 'admin/settings' => 'admin#settings'

  scope "admin" do
    resources :textpages, :except => :show
    resources :questions, :except => :show
    resources :posts, :except => :show
    resources :feedback, :except => [:create, :new, :edit, :update]
    resources :exchange, :except => [:create, :new, :edit, :update]
  end
  
  post 'sprypay/ipn' => 'sprypay#ipn'
  post 'sprypay/success' => 'sprypay#success'
  post 'sprypay/fail' => 'sprypay#fail'
  
  post '/ajax/do_not_show_info_win' => 'ajax#do_not_show_info_win'
  post '/ajax/check_info_win' => 'ajax#check_info_win'
  post '/ajax/like_post' => 'ajax#like_post'
  post '/ajax/check_like' => 'ajax#check_like'
  post '/ajax/subscribe_group' => 'ajax#subscribe_group'
  post '/ajax/check_subscribe' => 'ajax#check_subscribe'
  post '/ajax/update_balance' => 'ajax#update_balance'
  post '/ajax/service_repost' => 'ajax#service_repost'
  
  match "cabinet" => 'cabinet#index'
  get '/cabinet/orders'     => 'cabinet#orders'
  delete '/cabinet/orders'  => 'cabinet#orders'
  get '/cabinet/friends' => 'cabinet#friends'
  match '/cabinet/get_likes' => 'cabinet#get_likes'
  match '/cabinet/get_subscribers' => 'cabinet#get_subscribers'
  match '/cabinet/get_friends' => 'cabinet#get_friends'
 

  root :to => 'main#index'
  match 'faq' => 'main#faq'
  match 'buy' => 'main#buy'
  match 'blog' => 'main#blog'
  match 'blog/:id' => 'main#blog_details', :as => :blog_details
  get 'feedback' => 'main#feedback'
  post 'feedback' => 'main#feedback'
  match "/auth/:provider/callback" => "site_sessions#create"
  match "/signout" => "site_sessions#destroy", :as => :signout
  match "/auth/failure" => 'main#index'
  match '/cabinet/download_subscribers' => 'cabinet#download_subscribers' 
  post '/cabinet/check_like4me_subscribe' => 'cabinet#check_like4me_subscribe'
  post '/cabinet/download_list' => 'cabinet#download_list'
  match 'buy/(/:t)' => 'buy#index'
  get ':slug' => 'main#textpage'

end

app/models/download_orders.rb
class DownloadOrders < ActiveRecord::Base
  attr_accessible :count_users, :vkid, :user_id, :type
end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  attr_accessible :balance, :user_id, :wmr, :status
  
  validates :wmr, :presence => true,
            :format => { :with => /^R[0-9]{12}$/i }
            
  validates :balance, :presence => true,
            :numericality => { :only_integer => true, :greater_than_or_equal_to => 100 }
end

app/models/feedback.rb
# coding: utf-8

class Feedback < ActiveRecord::Base
  attr_accessible :email, :question, :read

  validates :email, :presence => true,
                    :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  validates :question, :presence => true
end

app/models/friend_order.rb
class FriendOrder < ActiveRecord::Base
  attr_accessible :balance, :bonus, :image, :name, :url, :user_id, :gender_min, :gender_max, :sex, :uid, :time_expiration
  
  validates :balance, :presence => true,
            :numericality => { :only_integer => true, :greater_than => 0 }
            
  validates :bonus, :presence => true,
            :numericality => { :only_integer => true, :greater_than => 0 }
            
  validates :url, :presence => true,
            :format => { :with => /^http[s]{0,1}:\/\/vk\.com\/.*$/i },
            :uniqueness => true
            
  def check_friend(access_token, uid)
    vk = VkontakteApi::Client.new(access_token)
    info = vk.friends.get(uid: uid)
    if self.uid.in?(info)
      return 1
    else
      return 0
    end
  end
  
  def calculate_time_expiration
    balance_in_seconds = self.balance.to_i*60.to_i
    self.time_expiration = Time.now.to_time.to_i+balance_in_seconds
  end
  
  def get_expiration_time
    exp_time = self.time_expiration.to_i - Time.now.to_time.to_i
    if exp_time >= 0 
      return (exp_time/60).to_i
    else
      return 0
    end
  end
end

app/models/like_order.rb
class LikeOrder < ActiveRecord::Base
  attr_accessible :balance, :gender_max, :gender_min, :name, :sex, :url, :item_id, :owner_id, :type_record, :user_id

  validates :balance, :presence => true,
  					  :numericality => { :only_integer => true, :greater_than => 0 }

  validates :name, :presence => true,
  				   :uniqueness => true
  validates :url, :presence => true,
  				  :format => { :with => /^http[s]{0,1}:\/\/vk\.com\/.*[-0-9]+_[0-9]+.*$/i },
  				  :uniqueness => true
end

app/models/payment.rb
# coding: utf-8
class Payment < ActiveRecord::Base
  attr_accessible :user_id, :amount, :status, :payment_num
  
  def create_url(spShopPaymentId, spAmount, spUserDataUserId)
    url = 'http://sprypay.ru/sppi/'
    url = url + '?spShopId=216377'
    url = url + '&spShopPaymentId='+spShopPaymentId
    url = url + '&spAmount='+spAmount
    url = url + '&spUserDataUserId='+spUserDataUserId
    url = url + '&spCurrency=rur'
    url = url + '&spPurpose=Покупка сердечек'
    url = url + '&lang=ru'
    return url
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :intro, :status, :title
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :question, :status
end

app/models/settings.rb
class Settings < ActiveRecord::Base
  attr_accessible :name, :value

  validates :name, :presence => true
  validates :value, :presence => true
end

app/models/site_user.rb
class SiteUser < ActiveRecord::Base
  attr_accessible :name, :provider, :uid, :balance, :sex, :birthday, :surprise, :info, :repost

def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["info"]["name"]
    user.balance = 50
    if defined?(auth["extra"]["raw_info"]["sex"]) && auth["extra"]["raw_info"]["sex"]
    	user.sex = auth["extra"]["raw_info"]["sex"].to_i
    end
    if defined?(auth["extra"]["raw_info"]["bdate"]) && auth["extra"]["raw_info"]["bdate"] && auth["extra"]["raw_info"]["bdate"].scan(/[0-9]+\.[0-9]+\.[0-9]{4}/i)
    	user.birthday = auth["extra"]["raw_info"]["bdate"]	
    end 
  end
end

end

app/models/tarif.rb
class Tarif < ActiveRecord::Base
  attr_accessible :hearts, :price, :table_num
end

app/models/textpage.rb
class Textpage < ActiveRecord::Base
  attr_accessible :content, :hidden, :slug, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password
  # attr_accessible :title, :body
end

app/models/vk_cities.rb
class VkCities < ActiveRecord::Base
  attr_accessible :city_id, :city_vkid, :city, :vkid
end

app/models/vk_countries.rb
class VkCountries < ActiveRecord::Base
  attr_accessible :country, :vkid
end

app/helpers/admin_helper.rb
module AdminHelper
	def get_settings_value(name)
	  	setting = Settings.find(:first, :conditions => { :name => name })
	  	return setting.value 
  	end
end

app/helpers/exchange_helper.rb
module ExchangeHelper
  def get_count_unread_exchange_orders
    return Exchange.count(:all, :conditions => { :status => 0 })
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
	def get_count_unread_message
		return Feedback.count(:all, :conditions => { :read => 0 })
	end

	def get_last_messages
		return Feedback.find(:all, :conditions => { :read => 0 })
	end
end

app/helpers/menu_helper.rb
module MenuHelper
	def is_current(cur_controller, cur_action, addition_condition)
	    if controller.controller_name == cur_controller && controller.action_name == cur_action && (addition_condition == nil || addition_condition.to_s == params[:id].to_s)
	        return 'active'
	    end
  end

  def is_current_textpage(cur_controller, cur_action, addition_condition)
    if controller.controller_name == cur_controller && controller.action_name == cur_action && (addition_condition == nil || addition_condition.to_s == params[:slug].to_s)
      return 'active'
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def get_last_posts
    @posts = Post.find(:all, :conditions => { :status => 0 }, :limit => 3, :order => 'id DESC' )
    return @posts
  end

  def get_last_posts_admin
    @posts = Post.find(:all, :conditions => { :status => 0 }, :limit => 10, :order => 'id DESC' )
    return @posts
  end
end

app/views/admin/settings.html.erb
<h4>Добавить новую константу</h4>
	<%= form_for(@settings, :method => 'post', :url => '',  :html => { :class => "form-horizontal" }) do |f| %>
	<div class="form-actions">
		<div class="control-group">
	  		<div class="controls">
				<!--<p class="text-error">Donec ullamcorper nulla non metus auctor fringilla.</p>
				<p class="text-error">Donec ullamcorper nulla non metus auctor fringilla.</p>
				<p class="text-error">Donec ullamcorper nulla non metus auctor fringilla.</p> -->
				<% @settings.errors.full_messages.each do |msg| %>
				    <p class="text-error"><%= msg %></p>
				<% end %>
			</div>
		</div>
		<div class="control-group">
	    <label class="control-label" for="param_name">Параметр</label>
	    <div class="controls">
	      	<%= f.text_field :name, :autofocus => true %>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="inputEmail">Значение</label>
	    <div class="controls">
	      <%= f.text_field :value %>
	    </div>
	  </div>
	  <div class="control-group">
	  	<div class="controls">
	  	<%= f.submit "Сохранить", :class => "btn btn-primary" %>
	  </div>
	  </div>
</div>

<table class="table table-striped">
  <thead>
  	<tr>
  		<th>Название</th>
  		<th>Значение</th>
  		<th></th>
  	</tr>
  </thead>
  <tbody>
  		<% @_settings.each do |param| %>
  		<tr>
  			<td><%= param.name %></td>
  			<td><%= param.value %></td>
  			<td>
  				<%= link_to image_tag('/im/delete.png'), {:controller => "admin", :action => "settings", :param_name => param.name} , :method => :delete, :confirm => 'Вы уверены в удалении?' %>
  				<%= link_to image_tag('/im/edit.png'), {:controller => "admin", :action => "settings", :param_name => param.name} , :method => :put %>
  			</td>
  		</tr>
  		<% end %>
  </tbody>
</table>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @meta_title %> — Like for me</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "main", :media => "all" %>
  <%= stylesheet_link_tag    "tip-violet/tip-violet.css", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "main" %>
  <%= javascript_include_tag "poshytip" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/favicon.ico" type="image/vnd.microsoft.icon"/>
  <% if current_user %>
  <script type="text/javascript">
  	$.ajax({
		url: '/cabinet/check_like4me_subscribe',
		type: 'post',
		dataType: 'json',
		success: function(response) 
		{
			if(response.error_code == 1)
				$("#info_like4me_subscribe").modal();
		}
		});
  <% end %>	
  </script>
</head>
<body>
<div class="container">
<div class="alert alert-info" style="height: 21px;display: none" id="notice-message-field">
  <div id="notice-message" style="float: left"></div>
  <button id="close-notice-button" class="btn btn-primary btn-mini" style="float: right;">Закрыть уведомление</button>
</div>
  <div class="masthead">
    <div class="loggin_vk" style="margin-top: 72px;">
      <% if current_user %>
        <span>Здравствуйте, </span><%= link_to current_user.name, '/cabinet' %> | <%= link_to "Выход", signout_path %>
      <% else %>
        <span><strong>Войти с помощью </strong></span>
        <a href="/auth/vkontakte" target=_blank><img src="/im/vkontakte.png"></a>
      <% end %>
    </div>
    <a href="/" style="text-decoration: none"><img src="/im/logo.png" width="220"></a>
    <% if current_user && current_user.repost == 0 %>
		<div id="repost-panel">
			<p>Сделай репост о нашем сервисе и получи в <strong>подарок 15 ♥</strong></p>
			<button class="btn btn-block btn-primary btn-buy" id="service-repost-btn">Сделать репост</button>
		</div>
	<% end %>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <ul class="nav">
            <% if current_user %>
              <li class="<%= is_current('cabinet', 'index', nil)%>"><a href="/cabinet">Кабинет</a></li>
            <% else %>
              <li class="<%= is_current('main', 'index', nil)%>"><a href="/">Главная</a></li>
            <% end %>  
            <li class="<%= is_current_textpage('main', 'buy', nil)%>"><a href="/buy">Цены</a></li>          
            <% get_available_text_page.each do |item| %>
                <li class="<%= is_current_textpage('main', 'textpage', item.slug)%>"><a href="/<%= item.slug %>"><%= item.title %></a></li>
            <% end %>
            <li class="<%= is_current_textpage('main', 'faq', nil)%>"><a href="/faq">FAQ</a></li>
            <li class="<%= is_current_textpage('main', 'blog', nil)%>"><a href="/blog">Блог</a></li>
            <li class="<%= is_current_textpage('main', 'feedback', nil)%>"><a href="/feedback">Написать нам</a></li>
            <!--<li><a href="#">Services</a></li>
            <li><a href="#">Downloads</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li> -->
          </ul>
        </div>
      </div>
    </div><!-- /.navbar -->
  </div>

  <%= yield %>
  <% if controller.action_name != 'blog' && controller.action_name != 'blog_details' %>
    <hr>
  <% end %>
  <!-- Example row of columns -->
  <% if controller.action_name != 'blog' && controller.action_name != 'blog_details' %>
  <div class="row-fluid">
    <% get_last_posts.each do |item| %>
    <div class="span4">
      <h4><%= item.title %></h4>
      <p><%= item.intro.html_safe %></p>
      <p><a class="btn btn-primary" href="/blog/<%= item.id %>">Подробнее &raquo;</a></p>
    </div>
    <% end %>
  </div>
  <% end %>

  <% if controller.action_name != 'blog' %>
      <hr>
  <% end %>

  <div class="footer">
    <p style="float: left">&copy; <%= get_settings_value('app_name') %> 2013 &mdash; 2014</p>
    <p style="float: right">Если у вас возникли вопросы вы можете <a href="/feedback">написать нам</a> или позвонить по телефону:<br /><strong>+7 (953) 324 15 19</strong></p>
    <div style="clear: both"></div>
  </div>
<!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='//counter.yadro.ru/hit?t38.6;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";"+Math.random()+
"' alt='' title='LiveInternet' "+
"border='0' width='31' height='31'><\/a>")
//--></script><!--/LiveInternet-->
</div> <!-- /container -->
<!-- modal window -->
<div class="modal fade" id="info_win" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Как получить бесплатно?</h4>
      </div>
      <div class="modal-body">
        <strong>Получить сердечки на баланс бесплатно очень просто!</strong><br /><br />
        <ul>
          <li>На главной странице своего кабинета, нажимайте кнопки<br /> "Поставить лайк" и "Вступить в группу".</li>
          <li>Ставьте лайки или вступайте в группы и получайте за это вознаграждение в виде сердечек на баланс абсолютно бесплатно.</li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- end modal -->

<!-- modal window -->
<div class="modal fade" id="info_balance" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="width: 580px;display: none">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Что такое баланс?</h4>
      </div>
      <div class="modal-body">
        <strong>Баланс или сердечки, </strong>
        которые у вас на счете, это условная единица сервиса.<br />Их вы можете тратить на использование функций
        данного сервиса в своих целях.<br />Серечки вы можете <a href="#" data-toggle="modal" data-target="#info_win" data-dismiss="modal">получать бесплатно</a> или <a href="/buy">покупать</a>.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- end modal -->

<!-- modal window -->
<div class="modal fade" id="info_like4me_subscribe" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Информация.</h4>
      </div>
      <div class="modal-body">
        Если вы хотите что бы это окно больше не появлялось,<br /><strong>вступите в группу нашего проекта</strong> <a href="https://vk.com/servicelike4me" onClick="popupWin = window.open(this.href, 'like4me', 'location,width=900,height=600,top=0'); popupWin.focus(); return false;">https://vk.com/servicelike4me</a>.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- end modal -->

<!-- surprise -->
<% if current_user and current_user.surprise and current_user.surprise > 0 %>
  <div class="modal fade" id="info_surprise" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Подарок</h4>
      </div>
      <div class="modal-body">
        <img src="/im/surprise.jpg" width="50" />
        На ваш баланс было <strong>начисленно <%= current_user.surprise %> сердечек</strong> в качестве <strong>подарка</strong>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
    $('#info_surprise').modal();
</script>
<% @site_user = SiteUser.find(:first, :conditions => {:id => current_user.id }) %>
<% @site_user.update_attributes(:surprise => '0') %>
<% end %>
<!-- end -->
<!-- exchange_modal_win> -->
<% if !@exchange.nil? %>
<div class="modal fade" id="exchange_win" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Обменять сердечки на реальные деньги.</h4>
      </div>
      <div class="modal-body">
       <% case  @exchange_show_form %>
       <% when -1%>
       		Вы должны быть авторизованы для выполнения данного действия
       <% when 2 %>
       		Ваша заявка принята и в данный момент обрабатывается		
       <% else %>
       		Оставьте заявку менеджеру на вывод средств и средства поступят на указанный вами кошелек в течении суток. Если возникнут какие-либо проблемы, то менеджер свяжется с вами.
       		<%= form_for(@exchange, :method => 'post', :url => '', :html => { :class => "form-horizontal", :style=>"margin-top: 20px;" }) do |f| %>
			  <% if @exchange.errors.any? %>
			    <div id="error_explanation">
			      <% @exchange.errors.full_messages.each do |msg| %>
			        <p class="text-error"><%= msg %></p>
			      <% end %>
			    </div>
			  <% end %>
			  <div class="control-group">
			    <label style="float: left">WMR кошелек</label>
			    <div class="controls" style="margin-left: 180px">
			      <%= f.text_field :wmr, :class=> 'order-form-input', :placeholder => "R234567891011", :title => 'Ваш R кошелек в системе Webmoney' %>
			    </div>
			  </div>
			  <div class="control-group">
			    <label style="float: left">Количество сердечек<br />для обмена</label>
			    <div class="controls" style="margin-left: 180px">
			      <%= f.text_field :balance, :class=> 'order-form-input', :placeholder => "100", :title => 'Количество сердечек для обмена' %>
			    </div>
			  </div>
			  <div class="control-group">
			    <div class="controls" style="margin-left: 180px">
			      <%= f.submit 'Отправить заявку', :class => 'btn btn-block', :style => 'width: 60%' %>
			    </div>
			  </div>
			  <p class="text-info-non-table" style="font-size: 12px;">Текущий курс обмена 1 ♥ = 50 коп.<br />Вывод производится только на кошельки WMR и при балансе более от 100 ♥</p>
			<% end %>
       <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<% if @exchange_show_form == 1 || @exchange_show_form == 2%>
	<script>
		$('#exchange_win').modal();	
	</script>
<% end %>
<% end %>
<!-- end modal -->
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter23721484 = new Ya.Metrika({id:23721484,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/23721484" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Like4me - Вход в административную панель</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/favicon.ico" type="image/vnd.microsoft.icon"/>
      <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>
</head>
<body>

<%= yield %>

</body>
</html>